-- Diseño inicial para un proyecto Supabase NUEVO, no ejecutar en PIT CRM.
-- Requiere Supabase Auth. Todas las tablas expuestas usan RLS.
create extension if not exists pgcrypto;
create table if not exists public.hub_organizations (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz not null default now());
create table if not exists public.hub_members (organization_id uuid not null references public.hub_organizations(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null check(role in('owner','admin','editor','viewer')), primary key(organization_id,user_id));
create table if not exists public.hub_brands(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.hub_organizations(id) on delete cascade,name text not null,created_at timestamptz not null default now());
create table if not exists public.hub_meta_assets(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.hub_organizations(id) on delete cascade,brand_id uuid references public.hub_brands(id) on delete set null,kind text not null check(kind in('ad_account','page','instagram_account')),external_id text not null,display_name text,metadata jsonb not null default '{}',unique(organization_id,kind,external_id));
create table if not exists public.hub_content(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.hub_organizations(id) on delete cascade,brand_id uuid not null references public.hub_brands(id) on delete cascade,title text not null,copy_text text not null default '',format text not null default 'image',status text not null default 'draft' check(status in('draft','approved','scheduled','publishing','published','failed')),created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.hub_publication_jobs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.hub_organizations(id) on delete cascade,content_id uuid not null references public.hub_content(id) on delete cascade,meta_asset_id uuid not null references public.hub_meta_assets(id) on delete cascade,scheduled_for timestamptz not null,status text not null default 'draft' check(status in('draft','queued','publishing','published','failed','cancelled')),attempts int not null default 0,external_post_id text,error_message text,idempotency_key uuid not null default gen_random_uuid() unique,created_at timestamptz not null default now());
create index if not exists hub_jobs_due_idx on public.hub_publication_jobs(status,scheduled_for);
-- No se guardan tokens de Meta en tablas accesibles por frontend. Usar secretos del backend o vault.
do $$ declare t text; begin foreach t in array array['hub_organizations','hub_members','hub_brands','hub_meta_assets','hub_content','hub_publication_jobs'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy hub_org_read on public.hub_organizations for select to authenticated using (exists(select 1 from public.hub_members m where m.organization_id=id and m.user_id=(select auth.uid())));
-- Policies for members must avoid recursive self-reference: manage membership server-side with vetted admin RPC/service backend.
create policy hub_brand_read on public.hub_brands for select to authenticated using (exists(select 1 from public.hub_members m where m.organization_id=hub_brands.organization_id and m.user_id=(select auth.uid())));
create policy hub_meta_read on public.hub_meta_assets for select to authenticated using (exists(select 1 from public.hub_members m where m.organization_id=hub_meta_assets.organization_id and m.user_id=(select auth.uid())));
create policy hub_content_read on public.hub_content for select to authenticated using (exists(select 1 from public.hub_members m where m.organization_id=hub_content.organization_id and m.user_id=(select auth.uid())));
create policy hub_content_insert on public.hub_content for insert to authenticated with check(created_by=(select auth.uid()) and exists(select 1 from public.hub_members m where m.organization_id=hub_content.organization_id and m.user_id=(select auth.uid()) and m.role in('owner','admin','editor')));
create policy hub_content_update on public.hub_content for update to authenticated using(exists(select 1 from public.hub_members m where m.organization_id=hub_content.organization_id and m.user_id=(select auth.uid()) and m.role in('owner','admin','editor'))) with check(exists(select 1 from public.hub_members m where m.organization_id=hub_content.organization_id and m.user_id=(select auth.uid()) and m.role in('owner','admin','editor')));
create policy hub_jobs_read on public.hub_publication_jobs for select to authenticated using(exists(select 1 from public.hub_members m where m.organization_id=hub_publication_jobs.organization_id and m.user_id=(select auth.uid())));
-- Job creation, mutation and publishing should be handled by server endpoint with organization authorization checks.
